# Generated by Django 5.2.5 on 2025-10-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='admin', max_length=10),
        ),
    ]
