# Generated by Django 5.2.5 on 2025-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], max_length=10),
        ),
    ]
